config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :reservations, only: [:index, :new, :create]
  end

  resources :reservations, except: [:new, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reservations

  validates :title, presence: true

  def update_availability
    if self.reservations.where("return_date IS NULL").empty?
      self.available = true
    else
      self.available = false
    end
    self.save!
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :book

  validates :book_id, :loan_date, :due_date, presence: true
  after_save :update_book_availability

  def update_book_availability
    self.book.update_availability
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
    render :new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to "/books"
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params["id"])
  end

  def show
    @book = Book.find(params["id"])
  end

  def update
    @book = Book.find(params["id"])
    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    Book.find(params["id"]).destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :publication_date, :available)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    if params[:book_id]
      @book = Book.find(params[:book_id])
      @reservations = @book.reservations
    else
      @reservations = Reservation.all
    end
  end

  def new
    @book = Book.find(params[:book_id])
    @reservation = @book.reservations.build
    @reservation.loan_date = Date.today
    @reservation.due_date = Date.today.next_month
    render :new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to "/reservations"
    else
      render :new
    end
  end

  def edit
    @reservation = Reservation.find(params["id"])
  end

  def show
    @reservation = Reservation.find(params["id"])
  end

  def update
    @reservation = Reservation.find(params["id"])
    if @reservation.update(reservation_params)
      redirect_to reservations_path
    else
      render :edit
    end
  end

  private

  def reservation_params
    if params[:reservation]
      params.require(:reservation).permit(:book_id, :loan_date, :due_date, :return_date)
    elsif params[:due_date]
      params.permit(:due_date)
    elsif params[:return_date]
      params.permit(:return_date)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1 class='well'>Edit Book Info</h1>

<% @book.errors.full_messages.each do |error| %>
  <div class='well alert alert-danger'><%= error %></div>
<% end %>

<div class='well'>
  <%= form_for @book do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_field :description,  class: 'form-control' %>

    <%= f.label :publication_date %>
    <%= f.date_field :publication_date,  class: 'form-control' %>

    <%= f.label :available %>
    <%= f.text_field :available,  class: 'form-control' %>
    <br>
    <%= f.submit class: "btn btn-primary"%>

    <% end %>
</div>

app/views/books/index.html.erb
<h1 class="well well-sm">Place of Books</h1>

<h4 class="well well-sm"><%= link_to "ADD New Book", new_book_path %></h4>

<table class="table table-responsive well">
  <thead>
    <tr>
      <th class="col-sx-3">Title</th>
      <th class="col-sx-1">Year</th>
      <th class="col-sx-3">Description</th>
      <th class="col-sx-1">Avaliable</th>
      <th class="col-sx-1"></th>
      <th class="col-sx-1"></th>
      <th class="col-sx-1"></th>
      <th class="col-sx-1"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book_path(book.id)%></td>
      <td><%= book.publication_date.strftime("%Y") %></td>
      <td><%= book.description %></td>
      <% if book.available == false %>
        <td><%= "No" %></td>
      <% else %>
        <td><%= "Yes" %></td>
      <% end %>
      <td class='btn btn-warning custom-width'><%= link_to "Delete", book_path(book.id), method: :delete %></td>
      <td class='btn btn-info custom-width'><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td class='btn btn-info custom-width'><%= link_to "Loans", book_reservations_path(book.id) %></td>
      <% if !book.available %>
        <td class='btn btn-info custom-width' disabled="disabled">Reserve</td>
      <% else %>
        <td class='btn btn-info custom-width'><%= link_to "Reserve", new_book_reservation_path(book.id) %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1 class='well'>New Book</h1>

<% @book.errors.full_messages.each do |error| %>
  <div class="well alert alert-danger"><%= error %></div>
<% end %>

<div class='well'>
  <%= form_for @book do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title,  class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_field :description,  class: 'form-control' %>

    <%= f.label :publication_date %>
    <%= f.date_field :publication_date,  class: 'form-control' %>

    <%= f.label :available %>
    <%= f.text_field :available,  class: 'form-control' %>

    <%= f.submit class: "btn btn-primary"%>

  <% end %>
</div?

app/views/books/show.html.erb
<h1 class='well'>Place of Books</h1>
<div class='well'>
  <%= link_to "All Books", books_path %>
</div>

<div class='well'>
  <button class='btn btn-info custom-width'><%= link_to "Loans", book_reservations_path(@book.id) %></button>
  <% if !@book.available %>
    <button class='btn btn-info custom-width' disabled="disabled">Reserve</button>
  <% else %>
    <button class='btn btn-info custom-width'><%= link_to "Reserve", new_book_reservation_path(@book.id) %></button>
  <% end %>
  <button class='btn btn-info custom-width'><%= link_to "Edit", edit_book_path(@book.id) %></button>
  <button class='btn btn-warning custom-width'><%= link_to "Delete", book_path(@book.id), method: :delete %></button>
  <h4>
    <%= @book.id %>:
    <%= @book.title %>
  </h4>
    <p><%= @book.publication_date.strftime("%Y") %></p>
    <% if @book.available == false %>
      <%= "On Loan" %>
    <% else %>
      <%= "Available" %>
    <% end %>
    <p><%= @book.description %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <!-- Internet Explorer Meta Tag - use edge rendering engine -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Viewport - for proper display on mobile devices -->
    <!-- Set to natural device width, with the scale of 100% (no shrinking) -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Bootstrap minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>PlaceOfBooks</title>
    <style type="text/css">
      body { background: #fbfbfb !important; }
      table { width:100%; }
      .custom-width {width: 65px !important; }
    </style>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reservations/edit.html.erb
<h1 class='well'>Edit Reservation</h1>

<% if @reservation.return_date == nil && @reservation.due_date < Time.now %>
  <h2 class="well well-sm alert alert-danger">Over Due!</h2>
<% end %>

<% @reservation.errors.full_messages.each do |error| %>
  <div class='well'><%= error %></div>
<% end %>

<h4 class='well'><%= @reservation.book.title %></h4>

<div class='well'>
  <%= form_for @reservation do |f| %>

    <%= f.label :loan_date %>
    <%= f.date_field :loan_date,  class: 'form-control' %>

    <%= f.label :due_date %>
    <%= f.date_field :due_date,  class: 'form-control' %>

    <%= f.label :return_date %>
    <%= f.date_field :return_date,  class: 'form-control' %>
    <br>
    <%= f.submit class: "btn btn-primary"%>

    <% end %>
</div>

app/views/reservations/index.html.erb
<h1 class="well well-sm">Place of Books - Reservations</h1>

<table class="table table-responsive well">
  <thead>
    <tr>
      <th class="col-sx-5">Book Title</th>
      <th class="col-sx-1">Loan Date</th>
      <th class="col-sx-1">Due Date</th>
      <th class="col-sx-1">Return Date</th>
      <th class="col-sx-1"></th>
      <th class="col-sx-1"></th>
      <th class="col-sx-1"></th>
      <th class="col-sx-1"></th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |r| %>
    <tr>
      <td><%= link_to r.book.title, book_path(r.book_id)%></td>
      <td><%= r.loan_date.strftime("%F") %></td>
      <td><%= r.due_date.strftime("%F") %></td>
      <% if r.return_date %>
        <td><%= r.return_date.strftime("%F") %></td>
      <% else %>
        <td> </td>
      <% end %>
      <td><button type='button' class='btn btn-info custom-width'><%= link_to 'Details', reservation_path(r.id) %></button></td>
      <td><button type='button' class='btn btn-info custom-width'><%= link_to 'Edit', edit_reservation_path(r.id) %></button></td>
      <% if r.return_date %>
        <td><button type='button' class='btn btn-info custom-width' disabled="disabled">Extend</button></td>
        <td><button type='button' class='btn btn-info custom-width' disabled="disabled">Return</button></td>
      <% else %>
        <td><button type='button' class='btn btn-info custom-width active'>
          <%= link_to "Extend", reservation_path(id:  r.id, due_date: Date.today.next_month), method: :patch %>
        </button></td>
        <td><button type='button' class='btn btn-info custom-width active'>
          <%= link_to "Return", reservation_path(id:  r.id, return_date: Date.today), method: :patch %>
        </button></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/reservations/new.html.erb
<h1 class='well'>New Reservation</h1>

<% @reservation.errors.full_messages.each do |error| %>
  <div class='well'><%= error %></div>
<% end %>

<h4 class='well'><%= @reservation.book.title %></h4>

<div class='well'>
  <%= form_for @reservation do |f| %>

    <%= f.label :loan_date %>
    <%= f.date_field :loan_date,  class: 'form-control' %>

    <%= f.label :due_date %>
    <%= f.date_field :due_date,  class: 'form-control' %>

    <%= f.label :return_date %>
    <%= f.date_field :return_date,  class: 'form-control' %>

    <%= f.hidden_field :book_id %> 
    <br>
    <%= f.submit class: "btn btn-primary"%>

    <% end %>
</div>

app/views/reservations/show.html.erb
<h1 class="well well-sm">Place of Books</h1>

<% if @reservation.return_date == nil && @reservation.due_date < Time.now %>
  <h2 class="well well-sm alert alert-danger">Over Due!</h2>
<% end %>

<p>Book Title:<%= link_to @reservation.book.title, book_path(@reservation.book_id)%></p>
<p>Loan Date:<%= @reservation.loan_date.strftime("%F") %></p>
<p>Due Date:<%= @reservation.due_date.strftime("%F") %></p>
<p>Return Date: <% if @reservation.return_date %> <%= @reservation.return_date.strftime("%F") %><<% end %></p>

<% unless @reservation.return_date %>
  <button type='button' class='btn btn-info active'>
    <%= link_to "Extend", reservation_path(id: @reservation.id, due_date:Date.today.next_month), method: :patch %>
  </button>
  <button type='button' class='btn btn-info active'>
    <%= link_to "Return", reservation_path(id:  @reservation.id, return_date: Date.today), method: :patch %>
  </button>

<% end %>